apiVersion: v1
kind: Service
metadata:
  name: load-balancer-ses-sqs-consumer-e8
  namespace: grupo-08-prod
spec:
  selector:
    app: ses-sqs-consumer-e8
  ports:
    - protocol: 'TCP'
      port: 8083
      targetPort: 8083
  type: LoadBalancer