- hosts: all
  tasks:
    - name: "Upload Files"
      copy:
        src: "prod-ses-sqs-consumer-deploy"
        dest: "/home/ubuntu/grupo08/"

    - name: "Apply secret-ses-sqs.yaml"
      shell: kubectl apply -f /home/ubuntu/grupo08/prod-ses-sqs-consumer-deploy/secret-ses-sqs.yaml -n grupo-08-prod

    - name: "Apply configmap-ses-sqs.yaml"
      shell: kubectl apply -f /home/ubuntu/grupo08/prod-ses-sqs-consumer-deploy/configmap-ses-sqs.yaml -n grupo-08-prod

    - name: "Apply clusterip-ses-sqs.yaml"
      shell: kubectl apply -f /home/ubuntu/grupo08/prod-ses-sqs-consumer-deploy/clusterip-ses-sqs.yaml -n grupo-08-prod

    - name: "Apply deployment-ses-sqs.yaml"
      shell: kubectl apply -f /home/ubuntu/grupo08/prod-ses-sqs-consumer-deploy/deployment-ses-sqs.yaml -n grupo-08-prod

    - name: "Apply hpa-ses-sqs.yaml"
      shell: kubectl apply -f /home/ubuntu/grupo08/prod-ses-sqs-consumer-deploy/hpa-ses-sqs.yaml -n grupo-08-prod